### ISSUE TITLE
i build it in eclipse have error 

### ISSUE THREAD

**Issue by ansjsun** [SpringDataElasticsearchDevs/spring-data-elasticsearch#31]
INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]  
[ERROR]   The project org.springframework.data:spring-data-elasticsearch:1.0.0.BUILD-SNAPSHOT (/Users/ansj/git/spring-data-elasticsearch/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find org.springframework.data.build:spring-data-parent:pom:1.1.0.BUILD-SNAPSHOT in http://repo.springsource.org/lib-snapshot-local was cached in the local repository, resolution will not be reattempted until the update interval of spring-libs-snapshot has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 10, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by mohsinh** [comment]
Sorry for late reply !

this project is moved to [SpringSource](https://github.com/SpringSource/spring-data-elasticsearch) 

and still if you are using the latest project then instead of  http://repo.springsource.org/lib-snapshot-local 
try http://repo.springsource.org/libs-snapshot/ repository 

have a look at this issue 

https://github.com/SpringSource/spring-data-elasticsearch/issues/1

Mohsin
